backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: "/assets"
public_folder: "photoPortfolio"

collections:
  - name: "photo"
    label: "photo"
    folder: "/assets"
    create: true
    slug: "{{year}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "image" }
